# This file is machine-generated - editing it directly is not advised

[[IdealGas]]
git-tree-sha1 = "09b95048a3a23c2c3573ae10ef3841288326731c"
repo-rev = "main"
repo-url = "https://github.com/andresegido/IdealGas.jl.git"
uuid = "30fbeecf-ffb7-46dc-b478-c8da4eefd92c"
version = "0.1.0"